import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import reactHooks from 'eslint-plugin-react-hooks';
import react from 'eslint-plugin-react';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default [
  js.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        URLSearchParams: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        Worker: 'readonly',
        crypto: 'readonly',
        confirm: 'readonly',
        alert: 'readonly',
        IDBDatabase: 'readonly',
        indexedDB: 'readonly',
        IDBOpenDBRequest: 'readonly',
        IDBTransaction: 'readonly',
        CryptoKey: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        BufferSource: 'readonly',
        DOMException: 'readonly',
        KeyboardEvent: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        HTMLCollection: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        MouseEvent: 'readonly',
        FocusEvent: 'readonly',
        InputEvent: 'readonly',
        WheelEvent: 'readonly',
        TouchEvent: 'readonly',
        PointerEvent: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        History: 'readonly',
        Location: 'readonly',
        Storage: 'readonly',
        Performance: 'readonly',
        MessageChannel: 'readonly',
        MessagePort: 'readonly',
        BroadcastChannel: 'readonly',
        WebSocket: 'readonly',
        XMLHttpRequest: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLInputElement: 'readonly',
        React: 'readonly',
        SVGElement: 'readonly',
        process: 'readonly',
        PromiseRejectionEvent: 'readonly',
        // vitest globals
        vi: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      'react-hooks': reactHooks,
      react,
      'jsx-a11y': jsxA11y,
    },
    settings: {
      // 显式版本号：eslint-plugin-react 的 'detect' 路径依赖旧版 context API
      // （contextOrFilename.getFilename），在 ESLint 10 下会抛 TypeError。
      react: { version: '19.0' },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-unused-vars': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/no-unescaped-entities': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'jsx-a11y/no-noninteractive-tabindex': 'off',
      'jsx-a11y/no-autofocus': 'off',
      'jsx-a11y/role-supports-aria-props': 'off',
      'jsx-a11y/no-interactive-element-to-noninteractive-role': 'off',
      'preserve-caught-error': 'off',
      '@typescript-eslint/preserve-caught-error': 'off',
      '@typescript-eslint/no-throw-literal': 'off',
      'no-case-declarations': 'off',
      'no-control-regex': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/use-memo': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'react-hooks/immutability': 'off',
      // ---- 安全相关规则 ----
      // 禁止 eval()
      'no-eval': 'error',
      // 禁止隐式 eval (setTimeout/setInterval 传字符串)
      'no-implied-eval': 'error',
      // 禁止 new Function()
      'no-new-func': 'error',
      // 禁止 __proto__
      'no-proto': 'error',
      // 禁止 caller/callee
      'no-caller': 'error',
      // 警告 console.log（鼓励使用结构化日志，但允许 warn/error/debug）
      'no-console': ['warn', { allow: ['warn', 'error', 'debug'] }],
      // 检测可能的 RegExp 注入
      'no-control-regex': 'error',
    },
  },
  {
    ignores: ['node_modules', 'dist', '.git', '*.js'],
  },
];
